services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rate_limiter:
    build:
      context: ./chat_bot_ratelimiter
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9001:9001"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:9001"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  envoy:
    image: envoyproxy/envoy:v1.34.1
    ports:
      - "127.0.0.1:10000:10000"
      - "127.0.0.1:9901:9901"
    volumes:
      - ./envoy-docker.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - backend
      - rate_limiter
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l info

volumes:
  redis_data: 