apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "request_id\":\"([^\"]+)"
          name: RequestID
          url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22envoy-proxy%5C%22%7D%20%7C%3D%20%5C%22$${__value.raw}%5C%22%22%7D%5D" 